### ISSUE TITLE
"Install" invisible with the current snapshot structure

### ISSUE THREAD

**Issue by Romaq** [xMamo/Minecraft-BareBones#1]
Expected per https://github.com/xMamo/minecraft-barebones/blob/master/readme.md
Quote:
  Log into your server and execute the following commands:
  /reload
  /function b7s:install

Actual result... /reload did fine, and /datapack list returns [file/BareBones.zip]
/function b7s:install returns "Unknown function b7s:install"

Per https://minecraft.gamepedia.com/Tag and https://www.minecraftforum.net/forums/minecraft-java-edition/redstone-discussion-and/commands-command-blocks-and/2876487-1-13-minecraft-functions-datapacks

I believe BareBones needs to be updated to support the tag format and have the "install" function called through the "minecraft:load" tag as discussed on the GamePedia Tag page above. My server also complained with lines such as the following:

01.04 21:50:17 [Server] ForkJoinPool.commonPool-worker-2/ERROR Couldn't load function at b7s:functions/advancement/_biome_beaches.mcfunction, though I do not know if the "install" function forces the other errors following. I'm just dipping my toes into this thing and using BareBones as a template for other features I am putting on my server.

**Comment by xmamo** [comment]
The latest version of Barebones is for Minecraft 17w43b. If you try to use the data pack for any version which is more recent, it won't work. The readme will be updated with the next release, that's why it still says "For Minecraft 1.13+". Sorry for the inconvenience.
Barebones for Minecraft 1.13 is currently under development. I haven't put out a release version yet, however you can take a look [here](https://github.com/xMamo/minecraft-barebones/tree/release/v1.0-mc18w11a). This version gets installed automatically without the need to call any special function (it does so by using the `minecraft:tick` tag, as you have described). I and my colleagues are still testing this version however, so I would advise waiting for the official release, which will probably be in a few days.

**Comment by xmamo** [comment]
I've put out a new release for Barebones. You can check it out [here](https://github.com/xMamo/minecraft-barebones/releases/tag/v1.0-mc18w11a).
Also, thank your other suggestions (#2, #3, #4, #5)! For now, I'm considering to implement #4 and #5 for the next release. If you like this project, please consider starring it ^^

**Comment by Romaq** [comment]
Thank you. I've already managed Glowing, Speed_Path, and God_Mode in my own "cfc3" data-pack as part of learning the ropes. I found https://www.planetminecraft.com/project/1-13-datapack-1-player-sleep-4078421/ though I'm not sure their methods are actually "best", plus if you did the One Player Sleeping, you would have a means to control how b7s thinks of "home" vs. "where I last slept in a bed.

A fully featured "road system" starting with Speed_Path should really be it's own 'thing'. I may take up that project as "Roads". The more you travel, the faster you *can* go depending upon how well built (investment cost) the "road" is and on how well "traveled" you are. Thank you for your work with BareBones. :)

**Comment by xmamo** [comment]
The data pack you sent me is more or less how I'm going to do it (I won't clear the weather, and I will add a configuration option to enable/disable this behaviour). As said, I'll also work on godmode!
You're right, a road system is probably not a "bare bones", a.k.a. minimal, standard, feature; therefore, it's best to be developed as a separate project. Thank you again and thanks for the star!

**Comment by Romaq** [comment]
Clearing the weather is a part of Vanilla sleeping, particularly with thunderstorms. It could be just after sunrise, but if a thunderstorm starts, you can immediately return to the bed, sleep until the next "day", and the weather will be clear and stop mobs from potentially spawning on the surface. Depending upon how you "wake" the player, letting the player stay in the bed naturally until "kicked" by the system... *NOT* clearing the weather may have the player remain in bed while you advance time through "days" of in-game time.

You can (and should) verify this behavior, but that is my understanding and why weather is commonly cleared with one-player-sleeping systems.

**Comment by xmamo** [comment]
You're right! Minecraft wiki confirms (https://minecraft.gamepedia.com/Bed#Passing_the_night). I'll therefore try to match vanilla Minecraft behaviour as close as I can. Thank you!
