### ISSUE TITLE
Suggestion: Speed_Path

### ISSUE THREAD

**Issue by Romaq** [xMamo/Minecraft-BareBones#2]
Suggestion for addition to this package or compatible add-on: Speed_Path

When a player is "on a grass path", grant Speed I for 10 seconds.

The purpose is to encourage grass path road building between locations. Further enhancements of this could be done to grant speed to players riding horses on a grass path. The effect time can be shortened to have it less overpowered, but still long enough for a player to cross the average stone or wooden bridge.

Other possible expansions of this idea could be like the video at https://www.youtube.com/watch?v=HktRyzmjATw which encourages the building of "roads" granting greater speed with more infrastructure investment.

**Comment by xmamo** [comment]
See #1
