### ISSUE TITLE
Suggestion: One Player Sleeping

### ISSUE THREAD

**Issue by Romaq** [xMamo/Minecraft-BareBones#5]
There are various command block versions of "One Player Sleeping". It would be useful if https://youtu.be/DOj_A3d9Akg were implemented in BareBones.

**Comment by xmamo** [comment]
Thanks for the suggestion. I already considered developing such functionality (https://github.com/xMamo/minecraft-barebones/projects/1). It will very probably be available in Barebones v1.1.

**Comment by xmamo** [comment]
See #1

**Comment by Romaq** [comment]
https://youtu.be/0jkaA1FfszI Advancement Popup Sleeping System for Servers Tutorial

Xisumavoid's video shows off a command function creation by Plagiatus, and it is NOT a data-pack, it only works in 1.12. Perhaps Plagiatus plans to make a data-pack. Would it interfere with BareBones once made into a data-pack?

**Comment by xmamo** [comment]
I published a new release for Barebones. It took quite a while, I was very busy. Anyhow, multiplayer bed should be ok!
Edit: I'll take a look at the video as soon as I can. Thanks again for all your suggestions!
