### ISSUE TITLE
tick -- "replace: false"?

### ISSUE THREAD

**Issue by Romaq** [xMamo/Minecraft-BareBones#6]
Per tick.json

{
	"values": [
		"b7s:tick"
	]
}

Should "replace": false, be in there so it wouldn't overwrite anyone else's "tick"? Or would this need to be loaded in before anyone else's?

**Comment by xmamo** [comment]
You're right, however `replace` defaults to `false`, as specified by the [Minecraft wiki](https://minecraft.gamepedia.com/Tag#JSON_format).

**Comment by Romaq** [comment]
Ah. I'm still learning the ropes on this thing.

**Comment by xmamo** [comment]
No problem!
