### ISSUE TITLE
Provarlo in giocatore singolo

### ISSUE THREAD

**Issue by MicheleIsoli** [xMamo/Minecraft-BareBones#7]
No, non è perchè sono povero, ma perchè non voglio creare un serever apposta.
Sono interessato a provarlo dato che ho guardato le ultime release e ho scaricato quella compatibile per la 1.12, il problema è che non ho MAI creato un server e non voglio farlo.

Volevo sapere solo se c'era un modo per installare il plugin in un mondo a giocatore singolo.

P.S. Quando torni su YouTube, che ci manchi?

**Comment by xmamo** [comment]
Sì, il plugin è installabile anche in singleplayer. Basta che apri la cartella di salvataggio del mondo ed inserisci nella sottocartella `datapacks` l'ultima versione del datapack `barebones.zip` che puoi ottenere da qui: https://github.com/xMamo/minecraft-barebones/releases/latest.

Per quanto riguarda YouTube, mi piacerebbe. Però non so come procedere, di tempo ne ho poco e Minecraft non lo tocco più. Sicuramente prima o poi riprenderò YouTube, ma probabilmente sarà su un altro canale dove faccio cose non correlate a Minecraft.

**Comment by MicheleIsoli** [comment]
Grazie mille!

Comunque se proprio non vorrà fare Minecraft, almeno i vecchi video non li cancelli per favore.
